<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */
declare(strict_types=1);

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Zend\Stdlib\AbstractOptions;

/**
 * Class Thumbnail
 * @package App\Entity
 *
 * @ORM\Embeddable
 */
class Thumbnail extends AbstractOptions
{
    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true)
     */
    private $path;

    /**
     * @var Size
     * @ORM\Embedded(class="App\Entity\Size")
     */
    private $size;

    /**
     * @return string
     */
    public function getPath(): string
    {
        return $this->path;
    }

    /**
     * @param string $path
     * @return Thumbnail
     */
    public function setPath(string $path): Thumbnail
    {
        $this->path = $path;
        return $this;
    }

    /**
     * @return Size
     */
    public function getSize(): Size
    {
        return $this->size;
    }

    /**
     * @param Size $size
     * @return Thumbnail
     */
    public function setSize(Size $size): Thumbnail
    {
        $this->size = $size;
        return $this;
    }

    /**
     * @return array
     */
    public function toArray(): array
    {
        // return parent::toArray(); // TODO: Change the autogenerated stub
        return [
            'path' => $this->getPath(),
            'size' => [
                'width' => $this->getSize()->getWidth(),
                'height' => $this->getSize()->getHeight(),
            ]
        ];
    }
}
